<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'BgOauthProvider\Module'                     => __DIR__ . '/Module.php',
    'BgOauthProvider\Acl'                        => __DIR__ . '/src/BgOauthProvider/Acl.php',
    'BgOauthProvider\Controller\OauthController' => __DIR__ . '/src/BgOauthProvider/Controller/OauthController.php',
    'BgOauthProvider\Entity\App'                 => __DIR__ . '/src/BgOauthProvider/Entity/App.php',
    'BgOauthProvider\Entity\AppInterface'        => __DIR__ . '/src/BgOauthProvider/Entity/AppInterface.php',
    'BgOauthProvider\Entity\AppNonce'            => __DIR__ . '/src/BgOauthProvider/Entity/AppNonce.php',
    'BgOauthProvider\Entity\Token'               => __DIR__ . '/src/BgOauthProvider/Entity/Token.php',
    'BgOauthProvider\Entity\TokenInterface'      => __DIR__ . '/src/BgOauthProvider/Entity/TokenInterface.php',
    'BgOauthProvider\Guard\Route'                => __DIR__ . '/src/BgOauthProvider/Guard/Route.php',
    'BgOauthProvider\Mapper\AppInterface'        => __DIR__ . '/src/BgOauthProvider/Mapper/AppInterface.php',
    'BgOauthProvider\Mapper\AppNonceInterface'   => __DIR__ . '/src/BgOauthProvider/Mapper/AppNonceInterface.php',
    'BgOauthProvider\Mapper\Doctrine\App'        => __DIR__ . '/src/BgOauthProvider/Mapper/Doctrine/App.php',
    'BgOauthProvider\Mapper\Doctrine\AppNonce'   => __DIR__ . '/src/BgOauthProvider/Mapper/Doctrine/AppNonce.php',
    'BgOauthProvider\Mapper\Doctrine\Token'      => __DIR__ . '/src/BgOauthProvider/Mapper/Doctrine/Token.php',
    'BgOauthProvider\Mapper\TokenInterface'      => __DIR__ . '/src/BgOauthProvider/Mapper/TokenInterface.php',
    'BgOauthProvider\Oauth\Provider'             => __DIR__ . '/src/BgOauthProvider/Oauth/Provider.php',
    'BgOauthProvider\Options\ModuleOptions'      => __DIR__ . '/src/BgOauthProvider/Options/ModuleOptions.php',
    'BgOauthProvider\Service\Oauth'              => __DIR__ . '/src/BgOauthProvider/Service/Oauth.php',
);