<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'BgOauthProvider\Module'                     => __DIR__ . '/Module.php',
    'BgOauthProvider\Acl'                        => __DIR__ . '/src/BgOauthProvider/Acl.php',
    'BgOauthProvider\Controller\OauthController' => __DIR__ . '/src/BgOauthProvider/Controller/OauthController.php',
    'BgOauthProvider\Entity\App'                 => __DIR__ . '/src/BgOauthProvider/Entity/App.php',
    'BgOauthProvider\Entity\AppInterface'        => __DIR__ . '/src/BgOauthProvider/Entity/AppInterface.php',
    'BgOauthProvider\Entity\AppNonce'            => __DIR__ . '/src/BgOauthProvider/Entity/AppNonce.php',
    'BgOauthProvider\Entity\Token'               => __DIR__ . '/src/BgOauthProvider/Entity/Token.php',
    'BgOauthProvider\Entity\TokenInterface'      => __DIR__ . '/src/BgOauthProvider/Entity/TokenInterface.php',
    'BgOauthProvider\Guard\Route'                => __DIR__ . '/src/BgOauthProvider/Guard/Route.php',
    'BgOauthProvider\Oauth\Provider'             => __DIR__ . '/src/BgOauthProvider/Oauth/Provider.php',
    'BgOauthProvider\Service\App'                => __DIR__ . '/src/BgOauthProvider/Service/App.php',
    'BgOauthProvider\Service\AppInterface'       => __DIR__ . '/src/BgOauthProvider/Service/AppInterface.php',
    'BgOauthProvider\Service\Oauth'              => __DIR__ . '/src/BgOauthProvider/Service/Oauth.php',
    'BgOauthProvider\Service\OauthInterface'     => __DIR__ . '/src/BgOauthProvider/Service/OauthInterface.php',
);