<h1>Oauth Authentication</h1>

<?php
$form = $this->authenticationForm;
$form->prepare();
?>

<?php echo $this->form()->openTag($form) ?>

<dl class="zend_form">

    <?php if(!$this->ZfcUserIdentity()): ?>

        <?php echo $this->formElementErrors($form->get('identity')) ?>

        <dt><?php echo $this->formLabel($form->get('identity')) ?></dt>
        <dd><?php echo $this->formInput($form->get('identity')) ?></dd>

        <dt><?php echo $this->formLabel($form->get('credential')) ?></dt>
        <dd><?php echo $this->formInput($form->get('credential')) ?></dd>

    <?php endif; ?>

    <dd><?php echo $this->formButton($form->get('submit')) ?></dd>
    <dd><?php echo $this->formButton($form->get('deny')) ?></dd>
</dl>

<?php echo $this->form()->closeTag() ?>
